### ISSUE TITLE
Remove duplicates

### ISSUE THREAD

**Issue by A1rPun** [BonoNL/malafidewebsites#3]
There are a few instances of duplicates, example:

```
cityplot-buiksloterham.nl
cityplot-buiksloterham.nl/
```
or
```
10urenvangrobbendonk.be
10urenvangrobbendonk.be
2host4you.be
2host4you.be
85jaarscoutinginaalst.be
85jaarscoutinginaalst.be
```

**Comment by A1rPun** [comment]
Maybe do something like this?

```shell
$ cat README.md | wc -l
3021
$ cat README.md | tr -d "/" | sort | uniq > out.md
$ cat out.md | wc -l
2681
```

**Comment by BonoNL** [comment]
I have no idea how this should work as I am no coder.
If you could explain to me or make it a PR I will learn and make it work.

**Comment by A1rPun** [comment]
Ah sorry for my assumption, I will explain. Het kan zelfs in het Nederlands ;)

In mijn comment laat ik zien hoe je in Linux het aantal regels van het bestand kan tellen. Het zijn er nu `3021` en na mijn acties waren het er nog maar `2681`.

De regel `cat README.md | tr -d "/" | sort | uniq > out.md` zal ik nu uitleggen:
- `cat README.md` output het bestand naar "standard output". Dit heeft als reden dat ik nu met pipes `|` de output kan bewerken.
 - `tr -d "/"` verwijderd alle slashes uit het bestand... er waren 3 URL's met een slash erachter, het leek me wel zo mooi om dat hetzelfde te houden.
- `sort` sorteerd de lijst zodat het volgende command zijn werk beter kan doen ;)
- `uniq` Haalt alle dubbele regels uit het bestand
- `> out.md` het word weggeschreven naar een bestand genaamd `out.md`

Hopelijk verduidelijkt dit mijn comments een beetje.
Ik kan een PR maken alleen zou het handig zijn als er iets word toegevoegd dat dezelfde stappen uitvoerd zodat de lijst netjes blijft als je er later iets aan toevoegd ;)
Zelfs dat kan ik voor je maken, iets wat onder Windows/Linux of Mac dezelfde stappen uitvoerd in een nodejs scriptje.
