### ISSUE TITLE
Overal *. voorzetten om alle domeinen te blokken.

### ISSUE THREAD

**Issue by BonoNL** [BonoNL/malafidewebsites#5]
Even tijd voor nemen

**Comment by A1rPun** [comment]
Ja inderdaad een goed idee.

Heb het in 1 command kunnen doen met:
```
sed -i.bak 's/^    /    \*\./' README.md
```

Kan wel weer een PR aanmaken ^^.

**Comment by BonoNL** [comment]
Hahaha ik wilde er vandaag voor gaan zitten om het met Calculator van Openoffice te doen.
Maar als jij het met een "simpel" command net zo makkelijk maakt als de laatste keer, dan zeg ik graag.

**Comment by A1rPun** [comment]
Nog even een vraag voordat ik een PR aanmaak. Met `pihole` kun je wildcard domains toevoegen door dit te doen `pihole -wild example.com`. Zou dat een betere manier zijn dan bij alle domeinnamen een `*.` toe te voegen? Dan laat je namelijk de gebruiker van de bloklijst kiezen of hij/zij ook alle subdomeinen wilt blokken.

**Comment by BonoNL** [comment]
Dat lijkt me inderdaad een betere manier. Laten we die maar doen, en bedankt voor je hulp.
